export const PromptData = [
  "印尼语中的 'dan' 是什么意思",
  "印尼语的 'atau' 和 'atau tidak' 有什么区别",
  "Bagaimana 和 Gimana 的区别是什么",
  "印尼语的 'mengapa' 和 'kenapa' 有什么区别",
  "印尼语的 'sama' 可以用在哪些场合",
  "Kamu 和 Anda 的区别是什么",
  "印尼语中 'saya' 和 'aku' 的用法有何不同",
  "印尼语里 'orang' 是什么意思",
  "印尼语中如何表达 '我喜欢你'",
  "印尼语的 'suka' 和 'cinta' 有什么区别",
  "Bagus 和 Baik 的区别是什么",
  "印尼语的 'sudah' 和 'belum' 是如何使用的",
  "印尼语中 'makan' 和 'memakan' 的区别是什么",
  "印尼语中的 'minum' 是什么意思",
  "印尼语的 'terima kasih' 可以如何回复",
  "印尼语的 'maaf' 和 'permisi' 什么时候用",
  "Bagaimana 用于疑问句时是什么意思",
  "印尼语的 'berapa' 用于什么场合",
  "Apa 和 Apakah 的区别是什么",
  "印尼语的 'di mana' 和 'ke mana' 有什么不同",
  "印尼语的 'dari mana' 和 'ke mana' 该如何使用",
  "印尼语的 'hari ini' 是什么意思",
  "印尼语中的 'kemarin' 和 'besok' 是什么",
  "印尼语中如何表示时间，例如 '现在'",
  "印尼语的 'senin' 和 'minggu' 是什么意思",
  "印尼语的 'bulan' 既可以表示月份，也可以表示月亮吗",
  "印尼语中 'tahun' 代表什么",
  "如何用印尼语表达 '今年' 和 '去年'",
  "印尼语的 'besar' 和 'kecil' 是什么意思",
  "印尼语的 'panjang' 和 'pendek' 怎么用",
  "印尼语的 'cepat' 和 'lambat' 代表什么意思",
  "印尼语的 'panas' 和 'dingin' 怎么用",
  "印尼语的 'mahal' 和 'murah' 有什么区别",
  "印尼语的 'baru' 和 'lama' 在不同语境下如何使用",
  "印尼语的 'ada' 和 'tidak ada' 是什么意思",
  "印尼语的 'punya' 和 'memiliki' 怎么用",
  "印尼语的 'bisa' 和 'boleh' 有什么不同",
  "印尼语中的 'harus' 和 'mesti' 有什么区别",
  "印尼语的 'mungkin' 和 'bisa jadi' 在表达可能性时有什么区别",
  "印尼语的 'karena' 和 'sebab' 如何使用",
  "印尼语的 'sebelum' 和 'sesudah' 代表什么意思",
  "印尼语的 'dekat' 和 'jauh' 如何使用",
  "印尼语的 'atas' 和 'bawah' 是什么意思",
  "印尼语的 'kiri' 和 'kanan' 代表什么意思",
  "印尼语中 'masuk' 和 'keluar' 代表什么意思",
  "印尼语的 'berjalan' 和 'berlari' 的区别是什么",
  "印尼语的 'tidur' 和 'bangun' 是什么意思",
  "印尼语中的 'belajar' 和 'mengajar' 有什么区别",
  "印尼语的 'membeli' 和 'menjual' 代表什么意思",
  "印尼语的 'melihat' 和 'menonton' 如何使用",
  "印尼语的 'mendengar' 和 'mendengarkan' 有什么区别",
  "印尼语的 'berbicara' 和 'mengobrol' 有何不同",
  "印尼语的 'memasak' 和 'memakan' 如何使用",
  "印尼语的 'menulis' 和 'membaca' 代表什么意思",
  "印尼语的 'mencuci' 和 'membersihkan' 有什么区别",
  "印尼语的 'bekerja' 和 'bermain' 代表什么",
  "印尼语的 'menunggu' 和 'mengantar' 是什么意思",
  "印尼语的 'memakai' 和 'melepaskan' 代表什么意思",
  "印尼语的 'membuka' 和 'menutup' 代表什么意思",
  "印尼语的 'menyukai' 和 'menyintai' 有什么不同",
  "印尼语中 'bahasa' 是什么意思",
  "印尼语中的 'hujan' 和 'panas' 代表什么意思",
  "印尼语的 'gelap' 和 'terang' 如何使用",
  "印尼语中的 'lama' 和 'cepat' 代表什么意思",
  "印尼语的 'berangkat' 和 'tiba' 是什么意思",
  "印尼语中如何说 '我想去印尼'",
  "印尼语的 'kembali' 和 'pergi' 有什么不同",
  "印尼语的 'dengan' 是介词还是动词",
  "印尼语的 'oleh' 和 'dari' 有什么区别",
  "印尼语的 'untuk' 和 'kepada' 什么时候用",
  "印尼语的 'dari' 和 'ke' 在表示方向时有什么不同",
  "印尼语的 'seperti' 和 'bagai' 如何使用",
  "印尼语的 'menurut' 和 'berdasarkan' 有何区别",
  "印尼语中 'sebab' 和 'akibat' 的用法不同吗",
  "印尼语的 'supaya' 和 'agar' 是什么意思",
  "印尼语的 'demi' 和 'untuk' 有什么区别",
  "印尼语的 'tanpa' 和 'dengan' 该如何使用",
  "印尼语的 'bahwa' 和 'yang' 有什么区别",
  "印尼语的 'jika' 和 'kalau' 代表什么",
  "印尼语的 'meskipun' 和 'walaupun' 该如何使用",
  "印尼语的 'tetapi' 和 'namun' 代表什么意思",
  "印尼语的 'sehingga' 和 'maka' 的区别是什么",
  "印尼语的 'ber-' 前缀通常用于什么情况",
  "印尼语的 'me-' 前缀有哪几种变化",
  "印尼语的 'pe-' 前缀如何影响词义",
  "印尼语的 'ter-' 和 'ke-' 词缀有什么区别",
  "印尼语的 'se-' 前缀可以用于哪些场合",
  "印尼语中如何构造被动语态",
  "印尼语的 'ke-an' 词缀有什么作用",
  "印尼语的 'per-an' 词缀如何使用",
  "印尼语的 'pe-an' 和 'ke-an' 词缀有什么区别",
  "印尼语里 'tidak' 和 'bukan' 到底该怎么选",
  "印尼语的 'dengan' 既是介词又是动词吗",
  "印尼语里什么时候必须加上 'ber-' 前缀",
  "印尼语的 'me-' 前缀变化规律是怎样的",
  "印尼语的 'saya' 和 'aku' 具体有什么不同，哪个更正式",
  "Kamu, Anda, Kalian 这些都表示 '你'，区别在哪",
  "怎么用印尼语自然地表达 '我不确定'",
  "印尼语里 'belum' 和 'tidak' 的否定方式有什么区别",
  "印尼语里 'hari ini' 和 'sekarang' 用法一样吗",
  "印尼语的 'masih' 和 'sudah' 该怎么用",
  "印尼语的 'pernah' 和 'sudah' 在句子里怎么选",
  "印尼语的 'karena' 和 'sebab' 语感上有什么不同",
  "印尼语里 'supaya' 和 'agar' 哪个更正式",
  "印尼语的 'kepada' 和 'untuk' 怎么区分",
  "印尼语里 'di'、'ke'、'dari' 表示方向时怎么用",
  "印尼语的 'seperti' 和 'bagai' 语感上有什么区别",
  "印尼语的 'menurut' 和 'berdasarkan' 在写作时如何选择",
  "印尼语的 'tanpa' 和 'dengan' 能搭配所有动词吗",
  "印尼语里 'walaupun' 和 'meskipun' 有语气区别吗",
  "印尼语的 'tetapi' 和 'namun' 在书面语和口语中的使用场景",
  "印尼语的 'sehingga' 和 'maka' 有什么不同",
  "印尼语里 'bertemu' 和 'menemui' 的区别是什么",
  "印尼语里 'melihat'、'menonton'、'menyaksikan' 怎么区分",
  "印尼语的 'mendengar' 和 'mendengarkan' 哪个是及物动词",
  "印尼语的 'berbicara'、'mengobrol' 和 'bercakap-cakap' 语气上有何不同",
  "印尼语的 'memasak' 和 'memakan' 为什么都带 'me-'",
  "印尼语里 'menulis' 和 'mengetik' 具体区别在哪里",
  "印尼语里 'mencuci'、'membersihkan' 和 'mengelap' 该怎么选",
  "印尼语里 'bekerja' 和 'berbisnis' 的区别",
  "印尼语的 'menunggu' 和 'mengantar' 有联系吗",
  "印尼语里 'memakai' 和 'menggunakan' 哪个更正式",
  "印尼语的 'membuka' 和 'menutup' 在比喻义上如何使用",
  "印尼语的 'bahasa' 只有 '语言' 这个意思吗",
  "印尼语里 'hujan' 和 'panas' 还能表达什么含义",
  "印尼语的 'gelap' 和 'terang' 除了光亮还能用在什么语境",
  "印尼语里 'berangkat' 和 'tiba' 在机场怎么用",
  "印尼语的 'pergi' 和 'kembali' 在口语里如何表达",
  "印尼语里 'dengan' 能代替 'dan' 吗",
  "印尼语的 'me-' 前缀什么时候会变成 'men-'",
  "印尼语的 'ber-' 词缀是怎么影响动词的",
  "印尼语的 'pe-' 词缀是不是专门用来构造职业名称的",
  "印尼语的 'ter-' 和 'ke-' 词缀的区别在哪里",
  "印尼语里 'ke-an' 结构可以自己造词吗",
  "印尼语里 'per-an' 结构和 'pe-an' 结构能互换吗",
  "印尼语的 'se-' 前缀通常用于什么情况",
  "印尼语里的被动语态是怎么构造的",
  "印尼语的 'boleh' 和 'bisa' 什么时候不能互换",
  "印尼语的 'mau' 和 'ingin' 语气上有什么区别",
  "印尼语里 'coba' 和 'mencoba' 如何用得更自然",
  "印尼语的 'hampir' 和 'nyaris' 哪个更正式",
  "印尼语的 'mungkin' 和 'barangkali' 该怎么选",
  "印尼语里的 'tapi' 和 'namun' 在口语中的使用频率",
  "印尼语的 'meskipun' 和 'kendati' 在正式写作中的用法",
  "印尼语的 'daripada' 除了比较还能怎么用",
  "印尼语的 'bukan hanya' 和 'tidak hanya' 有区别吗",
  "印尼语的 'kira-kira' 和 'sekitar' 都能表示大约吗",
  "印尼语的 'sedikit' 和 'beberapa' 的区别是什么",
  "印尼语的 'cukup' 和 'lumayan' 哪个更强调数量",
  "印尼语的 'hanya' 和 'saja' 在句子里如何选择",
  "印尼语的 'selama' 和 'sepanjang' 表示时间时有区别吗",
  "印尼语的 'tadi' 和 'barusan' 在时间表达上的差异",
  "印尼语的 'nanti' 和 'sebentar lagi' 在时间表达上的区别",
  "印尼语里的 'berikut' 和 'selanjutnya' 该怎么用",
  "印尼语的 'selama' 和 'sambil' 在句子里的区别",
  "印尼语的 'sambil' 和 'sementara' 什么时候不能互换",
  "印尼语的 'begitu' 和 'seperti itu' 语感上有什么区别",
  "印尼语的 'jika'、'kalau' 和 'apabila' 哪个最正式",
  "印尼语的 'walaupun' 和 'biarpun' 语气上有什么不同",
  "印尼语里的 'sekali' 和 'sangat' 可以互换吗",
  "印尼语的 'terlalu' 和 'amat' 在句子里如何使用",
  "印尼语的 'lebih' 和 'paling' 在比较级中怎么搭配",
  "印尼语的 'daripada' 和 'dibandingkan dengan' 有区别吗",
  "印尼语的 'semoga' 和 'mudah-mudahan' 哪个更正式",
  "印尼语的 'harap' 和 'berharap' 该如何使用",
  "印尼语的 'ayo' 和 'mari' 在邀请别人时有什么区别",
  "印尼语的 'sini' 和 'kesini' 有区别吗",
  "印尼语里的 'ke sana' 和 'ke situ' 该如何使用",
  "印尼语里的 'sedang' 和 'lagi' 在进行时态中的使用差别",
  "印尼语的 'dulu' 在句子里通常放哪里",
  "印尼语的 'bahkan' 和 'malah' 什么时候用",
  "印尼语的 'justru' 和 'malah' 在表达转折时有区别吗",
  "印尼语的 'mending' 和 'lebih baik' 在建议时怎么选"
]
